In [6]:
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing

In [4]:
spreadsheet = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
spreadsheet.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [9]:
enc = preprocessing.OrdinalEncoder()
transformed = enc.fit_transform(spreadsheet)
transformed

array([[5.375e+03, 0.000e+00, 0.000e+00, ..., 1.420e+02, 2.505e+03,
        0.000e+00],
       [3.962e+03, 1.000e+00, 0.000e+00, ..., 4.980e+02, 1.466e+03,
        0.000e+00],
       [2.564e+03, 1.000e+00, 0.000e+00, ..., 4.360e+02, 1.570e+02,
        1.000e+00],
       ...,
       [3.367e+03, 0.000e+00, 0.000e+00, ..., 1.370e+02, 2.994e+03,
        0.000e+00],
       [5.934e+03, 1.000e+00, 1.000e+00, ..., 7.950e+02, 2.660e+03,
        1.000e+00],
       [2.226e+03, 1.000e+00, 0.000e+00, ..., 1.388e+03, 5.407e+03,
        0.000e+00]])

In [10]:
scaler = preprocessing.StandardScaler().fit(transformed)
scaler

StandardScaler()

In [11]:
scaler.mean_

array([3.52100000e+03, 5.04756496e-01, 1.62146812e-01, 4.83032799e-01,
       2.99588244e-01, 3.23711487e+01, 9.03166264e-01, 9.40508306e-01,
       8.72923470e-01, 7.90004260e-01, 9.06431918e-01, 9.04444129e-01,
       7.97103507e-01, 9.85375550e-01, 9.92474798e-01, 6.90472810e-01,
       5.92219225e-01, 1.57432912e+00, 6.83524776e+02, 3.25779412e+03,
       2.65369871e-01])

In [12]:
scaler.scale_

array([2.03313895e+03, 4.99977375e-01, 3.68585436e-01, 4.99712031e-01,
       4.58077644e-01, 2.45577374e+01, 2.95731235e-01, 9.48486691e-01,
       7.37743961e-01, 8.59786459e-01, 8.80099984e-01, 8.79886380e-01,
       8.61489396e-01, 8.84939033e-01, 8.85027874e-01, 8.33696040e-01,
       4.91422033e-01, 1.06802818e+00, 4.78477549e+02, 1.88855941e+03,
       4.41529956e-01])

In [13]:
s_scaled = scaler.transform(transformed)
s_scaled

array([[ 0.91189045, -1.00955867, -0.43991649, ..., -1.13176632,
        -0.39860759, -0.60102348],
       [ 0.21690598,  0.99053183, -0.43991649, ..., -0.38773977,
        -0.94876238, -0.60102348],
       [-0.47070074,  0.99053183, -0.43991649, ..., -0.51731743,
        -1.64188328,  1.66382851],
       ...,
       [-0.07574495, -1.00955867, -0.43991649, ..., -1.14221613,
        -0.13968008, -0.60102348],
       [ 1.18683477,  0.99053183,  2.27315869, ...,  0.23297901,
        -0.31653445,  1.66382851],
       [-0.63694614,  0.99053183, -0.43991649, ...,  1.4723266 ,
         1.13801338, -0.60102348]])

In [14]:
s_scaled.mean()

-2.53416964573709e-18

In [15]:
print("mean:", s_scaled.mean(axis=0),", std:",  s_scaled.std(axis=0))

mean: [ 1.27369048e-17 -3.63190948e-17  3.11857123e-16 -5.87505497e-17
  3.15427555e-16 -2.67979432e-18 -2.79739000e-16  3.64909169e-16
  2.84799083e-16  5.35643595e-17  5.89680859e-16 -1.81847690e-16
 -1.81532420e-16 -1.13434117e-16 -5.64806062e-16  1.75290076e-17
 -9.22795057e-17 -5.42264263e-18 -2.98560615e-17  1.50383752e-17
 -1.65422127e-16] , std: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
